services:
    app:
        build: .
        ports:
            - "8088:8080"
        depends_on:
            db:
                condition: service_healthy

    db:
        image: postgres:18
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: mydb
        volumes:
            - postgres-data:/var/lib/postgresql
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U admin -d mydb"]
            interval: 5s
            retries: 5
            timeout: 10s


volumes:
    postgres-data: